version: "3.9"

services:
  s3:
    image: "bitnami/minio:latest"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=testuser
      - MINIO_ROOT_PASSWORD=testpassword
    volumes:
      - ./.docker/minio/data:/data
    restart: unless-stopped
